### PR TITLE
[ADMIN] Update lwm2m registry based on David Navarro email

### PR DESCRIPTION
**Pull request by jpradocueva**
This is what the changes look like.

image

This is the table suggested by David.
image

### CODE REVIEW

**Review by jmudge — COMMENTED** [review]
My comments are
1. The TS Core Appendix D.2.1 table has "Company Reserved" followed by "x" not "n/a".
2. In both the existing registry page and also the TS Core Appendix D.2.1 table the Description column enteries are left justified not centred.

**Comment by jpradocueva** [comment]
@jmudge thanks John. We have applied the first change. The alignment of the text to the left should be done automatically once it is published.

**Comment by gocadimic** [comment]
@jpradocueva, 
Should it be added ''n/a'' in the second row for the ''URN'' column, as added in the three last rows.

**Comment by jpradocueva** [comment]
@gocadimic yes, good catch!. Could you please submit a PR to add 'n/a'? Thanks

**Comment by gocadimic** [comment]
Missing "n/a" was added at a04c4eedaaea17aa4759373ddb55f1d5b810d357.

**Comment by jpradocueva** [comment]
Please note that ranges `10241 - 26240` and `26241 - 32768` are merged by this proposal.

**Pull request merged**
